### ISSUE TITLE
[Taking into account the User's location] Monster range and Player range

### ISSUE THREAD

**Issue by PKrystian** [PKrystian/FiveNightsEscape#15]
# Blocker*:
[Drawing the location of monsters near the User] Implement functionality to monster/s causing them to move closer to the user #9
Player base class #12
Monster base class #13 

## Description:
The purpose of  this issue is to implement the functionality to add "range" of monster/s or player ( circle range ).
Which after monster enter the player 'range', the player should lose one life.

## Objective:
- Look if there is already life system implemented, if not add it.
- Add player range ( circle ), which will be centered at user current location and will be placed in real-time.
- Add functionality that if monster enter said circle, the player will lose one life.

Update:

- Improve the 3rd type of monster that follows user. Implement their functionality.

## Additional Information:
Collaborate with the team in case of any questions or problems.
Test the functionality thoroughly to ensure there are no bugs related to this issue.

* blocker is a task that blocks the development of the current task, meaning this task can't be started if the blocker isn't finished.

**Comment by pmusielak** [comment]
Just change the range property in this:
```kt
Circle circle = map.addCircle(new CircleOptions()
.center(Monster_Object) //If my thinking is right (which it rarely is) if for the center of the circle we give an object the the circle should follow this object (I really hope it does)
.radius(10) //The radius is in meters
.strokeColor(Color.RED) //Color of the outline of the circle
.fillColor(Color.BLUE)); //Color to fill the circle. Is transparent by default
.visible(true) //Set the visibility of the circle
```
