### ISSUE TITLE
[Drawing the location of monsters near the User] Implement functionality to "spawn" monster/s near user location

### ISSUE THREAD

**Issue by PKrystian** [PKrystian/FiveNightsEscape#8]
# Blocker*:  [Detection of the User's location]: Real-time user location on map #2  

## Description:
Implement the functionality to draw the locations of monsters near the user current location in our Android application. This task involves integrating the necessary logic and UI elements to display the positions of monsters in proximity to the user.

## Objective:
- Monster/s location integration: Develop functionality to determine and display the positions of monster near the user.
- UI representation of monster locations: Implement UI elements or markers to visually represent the locations of monsters on the map interface.
- UI Consideration: Ensure the representation of monster locations aligns with the map UI design and provides relevant information to the user.

## Additional Information:
Collaborate with the team to discuss the visual representation of monster locations on the map.
Test the functionality thoroughly to ensure accurate placement and display of monster locations.
If issue #6 is completed, ensure the UI elements align to the mockup version of the application.

* blocker is a task that blocks the development of the current task, meaning this task can't be started if the blocker isn't finished.

**Comment by pmusielak** [comment]
Creating an attack area for the spawned monster
```kt
Circle circle = map.addCircle(new CircleOptions()
.center(Monster_Object) //If my thinking is right (which it rarely is) if for the center of the circle we give an object the the circle should follow this object (I really hope it does)
.radius(10) //The radius is in meters
.strokeColor(Color.RED) //Color of the outline of the circle
.fillColor(Color.BLUE)); //Color to fill the circle. Is transparent by default
.visible(true) //Set the visibility of the circle
```

**Comment by MBigaj** [comment]
Make use of the MonsterController class for spawning monsters
The main methods to use are:
monsterActivate -> Activates the monster behaviour ( mostly for the wandering monster since it has to start moving from point A to point B
monsterAlert -> Use every time on every monster nearby on updating the user position for checks if the player is in the monster range

**Comment by MBigaj** [comment]
For the spawning we could setup some kind of area for spawning with max spawn rate based on selected difficulty
Detection for when the user leaves an area to spawn more mobs - despawn mobs that are too far from the player and spawn new ones to match the spawn limit
spawn rate would be - certain chance for every mob to spawn with increasing chance for stronger monsters based on level and or difficulty selected

**Comment by PKrystian** [comment]
Issue completed in: https://github.com/PKrystian/FiveNightsEscape/pull/24
